# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asm_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.MainPannel = QtGui.QWidget(MainWindow)
        self.MainPannel.setMinimumSize(QtCore.QSize(800, 0))
        self.MainPannel.setObjectName(_fromUtf8("MainPannel"))
        self.SettingsPanel = QtGui.QGroupBox(self.MainPannel)
        self.SettingsPanel.setGeometry(QtCore.QRect(10, 10, 280, 270))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.SettingsPanel.setFont(font)
        self.SettingsPanel.setMouseTracking(False)
        self.SettingsPanel.setFlat(True)
        self.SettingsPanel.setCheckable(False)
        self.SettingsPanel.setObjectName(_fromUtf8("SettingsPanel"))
        self.LBLBaudRate = QtGui.QLabel(self.SettingsPanel)
        self.LBLBaudRate.setGeometry(QtCore.QRect(10, 70, 80, 30))
        self.LBLBaudRate.setObjectName(_fromUtf8("LBLBaudRate"))
        self.LBLSerialPort = QtGui.QLabel(self.SettingsPanel)
        self.LBLSerialPort.setGeometry(QtCore.QRect(10, 110, 80, 30))
        self.LBLSerialPort.setObjectName(_fromUtf8("LBLSerialPort"))
        self.SELSerialPort = QtGui.QComboBox(self.SettingsPanel)
        self.SELSerialPort.setGeometry(QtCore.QRect(100, 110, 170, 30))
        self.SELSerialPort.setObjectName(_fromUtf8("SELSerialPort"))
        self.SELSerialPort.addItem(_fromUtf8(""))
        self.BTNOpenPort = QtGui.QPushButton(self.SettingsPanel)
        self.BTNOpenPort.setGeometry(QtCore.QRect(100, 150, 80, 30))
        self.BTNOpenPort.setAutoDefault(False)
        self.BTNOpenPort.setFlat(False)
        self.BTNOpenPort.setObjectName(_fromUtf8("BTNOpenPort"))
        self.BTNClosePort = QtGui.QPushButton(self.SettingsPanel)
        self.BTNClosePort.setGeometry(QtCore.QRect(190, 150, 80, 30))
        self.BTNClosePort.setDefault(False)
        self.BTNClosePort.setFlat(False)
        self.BTNClosePort.setObjectName(_fromUtf8("BTNClosePort"))
        self.SELBaudRate = QtGui.QComboBox(self.SettingsPanel)
        self.SELBaudRate.setGeometry(QtCore.QRect(100, 70, 170, 30))
        self.SELBaudRate.setObjectName(_fromUtf8("SELBaudRate"))
        self.SELBaudRate.addItem(_fromUtf8(""))
        self.SELBaudRate.addItem(_fromUtf8(""))
        self.SELBaudRate.addItem(_fromUtf8(""))
        self.SELBaudRate.addItem(_fromUtf8(""))
        self.SELBaudRate.addItem(_fromUtf8(""))
        self.SELBaudRate.addItem(_fromUtf8(""))
        self.SELBaudRate.addItem(_fromUtf8(""))
        self.SELBaudRate.addItem(_fromUtf8(""))
        self.SELBaudRate.addItem(_fromUtf8(""))
        self.LBLSensorType = QtGui.QLabel(self.SettingsPanel)
        self.LBLSensorType.setGeometry(QtCore.QRect(10, 30, 80, 30))
        self.LBLSensorType.setObjectName(_fromUtf8("LBLSensorType"))
        self.SELSensor = QtGui.QComboBox(self.SettingsPanel)
        self.SELSensor.setGeometry(QtCore.QRect(100, 30, 170, 30))
        self.SELSensor.setObjectName(_fromUtf8("SELSensor"))
        self.SELSensor.addItem(_fromUtf8(""))
        self.SELSensor.addItem(_fromUtf8(""))
        self.SELSensor.addItem(_fromUtf8(""))
        self.SELSensor.addItem(_fromUtf8(""))
        self.SELSensor.addItem(_fromUtf8(""))
        self.LBLDelay = QtGui.QLabel(self.SettingsPanel)
        self.LBLDelay.setGeometry(QtCore.QRect(10, 190, 80, 30))
        self.LBLDelay.setObjectName(_fromUtf8("LBLDelay"))
        self.INDelay = QtGui.QLineEdit(self.SettingsPanel)
        self.INDelay.setGeometry(QtCore.QRect(100, 190, 170, 30))
        self.INDelay.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.INDelay.setObjectName(_fromUtf8("INDelay"))
        self.BTNSetDelay = QtGui.QPushButton(self.SettingsPanel)
        self.BTNSetDelay.setGeometry(QtCore.QRect(100, 230, 170, 30))
        self.BTNSetDelay.setCheckable(False)
        self.BTNSetDelay.setFlat(False)
        self.BTNSetDelay.setObjectName(_fromUtf8("BTNSetDelay"))
        self.Separator = QtGui.QFrame(self.MainPannel)
        self.Separator.setGeometry(QtCore.QRect(290, 0, 10, 600))
        self.Separator.setFrameShape(QtGui.QFrame.VLine)
        self.Separator.setFrameShadow(QtGui.QFrame.Sunken)
        self.Separator.setObjectName(_fromUtf8("Separator"))
        self.DisplayPanel = QtGui.QGroupBox(self.MainPannel)
        self.DisplayPanel.setGeometry(QtCore.QRect(300, 10, 490, 580))
        self.DisplayPanel.setObjectName(_fromUtf8("DisplayPanel"))
        self.verticalLayoutWidget = QtGui.QWidget(self.DisplayPanel)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 471, 461))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.PlotLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.PlotLayout.setContentsMargins(0, -1, -1, -1)
        self.PlotLayout.setSpacing(0)
        self.PlotLayout.setObjectName(_fromUtf8("PlotLayout"))
        self.LDCTime = QtGui.QLCDNumber(self.DisplayPanel)
        self.LDCTime.setGeometry(QtCore.QRect(10, 30, 110, 30))
        self.LDCTime.setAutoFillBackground(False)
        self.LDCTime.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LDCTime.setFrameShadow(QtGui.QFrame.Sunken)
        self.LDCTime.setLineWidth(1)
        self.LDCTime.setSmallDecimalPoint(True)
        self.LDCTime.setObjectName(_fromUtf8("LDCTime"))
        self.LBLTime = QtGui.QLabel(self.DisplayPanel)
        self.LBLTime.setGeometry(QtCore.QRect(10, 70, 110, 30))
        self.LBLTime.setObjectName(_fromUtf8("LBLTime"))
        self.LCDMagnitude1 = QtGui.QLCDNumber(self.DisplayPanel)
        self.LCDMagnitude1.setGeometry(QtCore.QRect(130, 30, 110, 30))
        self.LCDMagnitude1.setAutoFillBackground(False)
        self.LCDMagnitude1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LCDMagnitude1.setFrameShadow(QtGui.QFrame.Sunken)
        self.LCDMagnitude1.setLineWidth(1)
        self.LCDMagnitude1.setSmallDecimalPoint(True)
        self.LCDMagnitude1.setObjectName(_fromUtf8("LCDMagnitude1"))
        self.LBLMagnitude1 = QtGui.QLabel(self.DisplayPanel)
        self.LBLMagnitude1.setGeometry(QtCore.QRect(130, 70, 110, 30))
        self.LBLMagnitude1.setObjectName(_fromUtf8("LBLMagnitude1"))
        self.LCDMagnitude2 = QtGui.QLCDNumber(self.DisplayPanel)
        self.LCDMagnitude2.setGeometry(QtCore.QRect(250, 30, 110, 30))
        self.LCDMagnitude2.setAutoFillBackground(False)
        self.LCDMagnitude2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LCDMagnitude2.setFrameShadow(QtGui.QFrame.Sunken)
        self.LCDMagnitude2.setLineWidth(1)
        self.LCDMagnitude2.setSmallDecimalPoint(True)
        self.LCDMagnitude2.setObjectName(_fromUtf8("LCDMagnitude2"))
        self.LBLMagnitude2 = QtGui.QLabel(self.DisplayPanel)
        self.LBLMagnitude2.setGeometry(QtCore.QRect(250, 70, 110, 30))
        self.LBLMagnitude2.setObjectName(_fromUtf8("LBLMagnitude2"))
        self.LCDMagnitude3 = QtGui.QLCDNumber(self.DisplayPanel)
        self.LCDMagnitude3.setGeometry(QtCore.QRect(370, 30, 110, 30))
        self.LCDMagnitude3.setAutoFillBackground(False)
        self.LCDMagnitude3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LCDMagnitude3.setFrameShadow(QtGui.QFrame.Sunken)
        self.LCDMagnitude3.setLineWidth(1)
        self.LCDMagnitude3.setSmallDecimalPoint(True)
        self.LCDMagnitude3.setObjectName(_fromUtf8("LCDMagnitude3"))
        self.LBLMagnitude3 = QtGui.QLabel(self.DisplayPanel)
        self.LBLMagnitude3.setGeometry(QtCore.QRect(370, 70, 110, 30))
        self.LBLMagnitude3.setObjectName(_fromUtf8("LBLMagnitude3"))
        self.SerialConsolePanel = QtGui.QGroupBox(self.MainPannel)
        self.SerialConsolePanel.setGeometry(QtCore.QRect(10, 290, 281, 301))
        self.SerialConsolePanel.setObjectName(_fromUtf8("SerialConsolePanel"))
        self.SerialConsole = QtGui.QTextEdit(self.SerialConsolePanel)
        self.SerialConsole.setGeometry(QtCore.QRect(10, 30, 261, 261))
        self.SerialConsole.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SerialConsole.setFrameShadow(QtGui.QFrame.Sunken)
        self.SerialConsole.setLineWidth(1)
        self.SerialConsole.setReadOnly(True)
        self.SerialConsole.setObjectName(_fromUtf8("SerialConsole"))
        MainWindow.setCentralWidget(self.MainPannel)

        self.retranslateUi(MainWindow)
        self.SELBaudRate.setCurrentIndex(0)
        self.SELSensor.setCurrentIndex(0)
        QtCore.QObject.connect(self.SELSensor, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.SELSensor.setCurrentIndex)
        QtCore.QObject.connect(self.SELBaudRate, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.SELBaudRate.setCurrentIndex)
        QtCore.QObject.connect(self.SELSerialPort, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.SELSerialPort.setCurrentIndex)
        QtCore.QObject.connect(self.BTNOpenPort, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BTNOpenPort.click)
        QtCore.QObject.connect(self.BTNClosePort, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BTNClosePort.click)
        QtCore.QObject.connect(self.INDelay, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), self.INDelay.setText)
        QtCore.QObject.connect(self.BTNSetDelay, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BTNSetDelay.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.SELSensor, self.SELBaudRate)
        MainWindow.setTabOrder(self.SELBaudRate, self.SELSerialPort)
        MainWindow.setTabOrder(self.SELSerialPort, self.BTNOpenPort)
        MainWindow.setTabOrder(self.BTNOpenPort, self.BTNClosePort)
        MainWindow.setTabOrder(self.BTNClosePort, self.INDelay)
        MainWindow.setTabOrder(self.INDelay, self.BTNSetDelay)
        MainWindow.setTabOrder(self.BTNSetDelay, self.SerialConsole)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Aruino Serial Monitor", None))
        MainWindow.setToolTip(_translate("MainWindow", "Arduino Serial Monitor", None))
        self.SettingsPanel.setTitle(_translate("MainWindow", "Settings", None))
        self.LBLBaudRate.setText(_translate("MainWindow", "Baud Rate", None))
        self.LBLSerialPort.setText(_translate("MainWindow", "Serial Port", None))
        self.SELSerialPort.setItemText(0, _translate("MainWindow", "Select port", None))
        self.BTNOpenPort.setText(_translate("MainWindow", "Open Port", None))
        self.BTNClosePort.setText(_translate("MainWindow", "Close Port", None))
        self.SELBaudRate.setItemText(0, _translate("MainWindow", "Select baud rate", None))
        self.SELBaudRate.setItemText(1, _translate("MainWindow", "4800 baud", None))
        self.SELBaudRate.setItemText(2, _translate("MainWindow", "9600 baud", None))
        self.SELBaudRate.setItemText(3, _translate("MainWindow", "19200  baud", None))
        self.SELBaudRate.setItemText(4, _translate("MainWindow", "38400  baud", None))
        self.SELBaudRate.setItemText(5, _translate("MainWindow", "57600  baud", None))
        self.SELBaudRate.setItemText(6, _translate("MainWindow", "115200  baud", None))
        self.SELBaudRate.setItemText(7, _translate("MainWindow", "230400  baud", None))
        self.SELBaudRate.setItemText(8, _translate("MainWindow", "250000  baud", None))
        self.LBLSensorType.setText(_translate("MainWindow", "Sensor Type", None))
        self.SELSensor.setItemText(0, _translate("MainWindow", "Select sensor", None))
        self.SELSensor.setItemText(1, _translate("MainWindow", "Accelerometer", None))
        self.SELSensor.setItemText(2, _translate("MainWindow", "Barometer", None))
        self.SELSensor.setItemText(3, _translate("MainWindow", "Thermohygrometer", None))
        self.SELSensor.setItemText(4, _translate("MainWindow", "Ultrasonic Rangin Sensor", None))
        self.LBLDelay.setText(_translate("MainWindow", "Delay", None))
        self.BTNSetDelay.setText(_translate("MainWindow", "Set Delay", None))
        self.DisplayPanel.setTitle(_translate("MainWindow", "Plot and display", None))
        self.LBLTime.setText(_translate("MainWindow", "Time", None))
        self.LBLMagnitude1.setText(_translate("MainWindow", "Magnitude 1", None))
        self.LBLMagnitude2.setText(_translate("MainWindow", "Magnitude 2", None))
        self.LBLMagnitude3.setText(_translate("MainWindow", "Magnitude 3", None))
        self.SerialConsolePanel.setTitle(_translate("MainWindow", "Serial Monitor", None))

